package area

import "github.com/darabuchi/utils/language"

var (
	// AirPortMap https://zh.wikipedia.org/zh-cn/%E5%9B%BD%E9%99%85%E8%88%AA%E7%A9%BA%E8%BF%90%E8%BE%93%E5%8D%8F%E4%BC%9A%E6%9C%BA%E5%9C%BA%E4%BB%A3%E7%A0%81_(A)
	AirPortMap = map[string]AirPortInfo{
		"AAA": {
			Code:            "AAA",
			Icao:            "NTGA",
			Name:            "Anaa Airport",
			CountryCode:     "PF",
			Timezone:        CountryCodeMap["PF"].Timezone,
			CountryI18nName: CountryCodeMap["PF"].I18nName,
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "阿纳机场",
				language.ChineseCN:   "阿纳机场",
				language.ChineseHans: "阿纳机场",
				language.ChineseHant: "阿納機場",
				language.English:     "Anaa Airport",
				language.French:      "Aéroport d'Anaa",
				language.German:      "Flughafen Anaa",
				language.Japanese:    "アナア空港",
				language.Korean:      "아나아 공항",
				language.Russian:     "Аэропорт Анаа",
			},
		},
		"AAB": {
			Code:            "AAB",
			Icao:            "YARY",
			Name:            "Arrabury Airport",
			CountryCode:     "AU",
			Timezone:        CountryCodeMap["AU"].Timezone,
			CountryI18nName: CountryCodeMap["AU"].I18nName,
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "阿拉贝里机场",
				language.ChineseCN:   "阿拉贝里机场",
				language.ChineseHans: "阿拉贝里机场",
				language.ChineseHant: "阿拉貝里機場",
				language.English:     "Arrabury Airport",
				language.French:      "Aéroport d'Arrabury",
				language.German:      "Flughafen Arrabury",
				language.Japanese:    "アラバリー空港",
				language.Korean:      "아라바리 공항",
				language.Russian:     "Аэропорт Аррабури",
			},
		},
		"AAC": {
			Code:            "AAC",
			Icao:            "HEAT",
			Name:            "El Arish International Airport",
			CountryCode:     "EG",
			Timezone:        CountryCodeMap["EG"].Timezone,
			CountryI18nName: CountryCodeMap["EG"].I18nName,
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "埃拉希国际机场",
				language.ChineseCN:   "埃拉希国际机场",
				language.ChineseHans: "埃拉希国际机场",
				language.ChineseHant: "埃拉希國際機場",
				language.English:     "El Arish International Airport",
				language.French:      "Aéroport international d'El Arish",
				language.German:      "El Arish International Airport",
				language.Japanese:    "エル・アリシュ国際空港",
				language.Korean:      "엘 아리쉬 국제공항",
				language.Russian:     "Международный аэропорт Эль-Ариш",
			},
		},
		"AAD": {
			Code:            "AAD",
			Icao:            "HAGD",
			Name:            "Adado Airport",
			CountryCode:     "SO",
			Timezone:        CountryCodeMap["SO"].Timezone,
			CountryI18nName: CountryCodeMap["SO"].I18nName,
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "阿达多机场",
				language.ChineseCN:   "阿达多机场",
				language.ChineseHans: "阿达多机场",
				language.ChineseHant: "阿達多機場",
				language.English:     "Adado Airport",
				language.French:      "Aéroport d'Adado",
				language.German:      "Adado Airport",
				language.Japanese:    "アダド空港",
				language.Korean:      "아다도 공항",
				language.Russian:     "Аэропорт Ададо",
			},
		},
		"AAE": {
			Code:            "AAE",
			Icao:            "DAUA",
			Name:            "Annaba–Rabah Bitat Airport",
			CountryCode:     "DZ",
			Timezone:        CountryCodeMap["DZ"].Timezone,
			CountryI18nName: CountryCodeMap["DZ"].I18nName,
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "安纳巴机场",
				language.ChineseCN:   "安纳巴机场",
				language.ChineseHans: "安纳巴机场",
				language.ChineseHant: "安納巴機場",
				language.English:     "Annaba–Rabah Bitat Airport",
				language.French:      "Aéroport d'Annaba",
				language.German:      "Annaba–Rabah Bitat Airport",
				language.Japanese:    "アンナバ空港",
				language.Korean:      "안나바 공항",
				language.Russian:     "Аэропорт Аннаба",
			},
		},
		"AAF": {
			Code:            "AAF",
			Icao:            "KAAF",
			Name:            "Apalachicola Regional Airport",
			CountryCode:     "US",
			Timezone:        CountryCodeMap["US"].Timezone,
			CountryI18nName: CountryCodeMap["US"].I18nName,
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "阿帕拉奇科拉地区机场",
				language.ChineseCN:   "阿帕拉奇科拉地区机场",
				language.ChineseHans: "阿帕拉奇科拉地区机场",
				language.ChineseHant: "阿帕拉奇科拉地區機場",
				language.English:     "Apalachicola Regional Airport",
				language.French:      "Aéroport régional d'Apalachicola",
				language.German:      "Apalachicola Regional Airport",
				language.Japanese:    "アパラキコラ地方空港",
				language.Korean:      "아파라키콜라 지방 공항",
				language.Russian:     "Аэропорт Апалачикола",
			},
		},
		"AAG": {
			Code:            "AAG",
			Icao:            "SWAG",
			Name:            "Araranguá Airport",
			CountryCode:     "BR",
			Timezone:        CountryCodeMap["BR"].Timezone,
			CountryI18nName: CountryCodeMap["BR"].I18nName,
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "阿拉朗瓜机场",
				language.ChineseCN:   "阿拉朗瓜机场",
				language.ChineseHans: "阿拉朗瓜机场",
				language.ChineseHant: "阿拉朗瓜機場",
				language.English:     "Araranguá Airport",
				language.French:      "Aéroport d'Araranguá",
				language.German:      "Araranguá Airport",
				language.Japanese:    "アラランガ空港",
				language.Korean:      "아라랑가 공항",
				language.Russian:     "Аэропорт Арарангуа",
			},
		},
		"AAH": {
			Code:            "AAH",
			Icao:            "EDKA",
			Name:            "Aachen-Merzbrück Airport",
			CountryCode:     "DE",
			Timezone:        CountryCodeMap["DE"].Timezone,
			CountryI18nName: CountryCodeMap["DE"].I18nName,
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "阿赫森-梅尔兹布鲁克机场",
				language.ChineseCN:   "阿赫森-梅尔兹布鲁克机场",
				language.ChineseHans: "阿赫森-梅尔兹布鲁克机场",
				language.ChineseHant: "阿赫森-梅爾茲布魯克機場",
				language.English:     "Aachen-Merzbrück Airport",
				language.French:      "Aéroport d'Aix-la-Chapelle-Merzbrück",
				language.German:      "Aachen-Merzbrück Airport",
				language.Japanese:    "アッセン＝メルツブリュック空港",
				language.Korean:      "아헨-메르츠브루크 공항",
				language.Russian:     "Аэропорт Аахен-Мерцбрюк",
			},
		},
	}
)
