package area

import (
	"github.com/darabuchi/utils/language"
)

var (
	CountryCodeMap = map[string]*CountryInfo{
		"": {
			Code:             "",
			Name:             "",
			TelCode:          "",
			Domain:           "",
			Banner:           "🏴‍☠️",
			ISO2:             "",
			ISO3:             "",
			ISO3166:          "",
			STANAG:           "",
			GEC:              "",
			Capital:          "",
			NationalLanguage: language.English,
			Languages: []language.LanguageCode{
				language.English,
			},
			Currency: "USD", // $, 美元
			Timezone: UTC,
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "未知",
				language.ChineseHans: "未知",
				language.ChineseHant: "未知",
				language.English:     "Unknown",
				language.French:      "Inconnu",
				language.German:      "Unbekannt",
				language.Japanese:    "不明",
				language.Korean:      "미알림",
				language.Russian:     "Неизвестно",
				language.Spanish:     "Desconocido",
			},
		},

		// 常用国家代码列表
		"CN": {
			Code:             "CN",
			Name:             "中国",
			TelCode:          "+86",
			Domain:           ".cn",
			Banner:           "🇨🇳",
			ISO2:             "CN",
			ISO3:             "CHN",
			ISO3166:          "156",
			STANAG:           "CHN",
			GEC:              "CH",
			Capital:          "北京",
			NationalLanguage: language.Chinese,
			Languages: []language.LanguageCode{
				language.Chinese,
			},
			Currency: "CNY", // ¥, 人民币
			Timezone: AsiaShanghai,
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "中国",
				language.ChineseHans: "中国",
				language.ChineseHant: "中國",
				language.English:     "China",
				language.French:      "Chine",
				language.German:      "China",
				language.Japanese:    "中国",
				language.Korean:      "중국",
				language.Russian:     "Китай",
				language.Spanish:     "China",
			},
		},
		"US": {
			Code:             "US",
			Name:             "United States",
			TelCode:          "+1",
			Domain:           ".us",
			Banner:           "🇺🇸",
			ISO2:             "US",
			ISO3:             "USA",
			ISO3166:          "840",
			STANAG:           "USA",
			GEC:              "US",
			Capital:          "Washington, D.C.",
			NationalLanguage: language.English,
			Languages: []language.LanguageCode{
				language.English,
			},
			Currency: "USD", // $, 美元
			Timezone: UTC,
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "美国",
				language.ChineseHans: "美国",
				language.ChineseHant: "美國",
				language.English:     "United States",
				language.French:      "États-Unis",
				language.German:      "Vereinigte Staaten von Amerika",
				language.Japanese:    "アメリカ合衆国",
				language.Korean:      "미국",
				language.Russian:     "Соединенные Штаты Америки",
				language.Spanish:     "Estados Unidos",
			},
		},
		"JP": {
			Code:             "JP",
			Name:             "日本",
			TelCode:          "+81",
			Domain:           ".jp",
			Banner:           "🇯🇵",
			ISO2:             "JP",
			ISO3:             "JPN",
			ISO3166:          "392",
			STANAG:           "JPN",
			GEC:              "JA",
			Capital:          "东京",
			NationalLanguage: language.Japanese,
			Languages: []language.LanguageCode{
				language.Japanese,
			},
			Currency: "JPY", // ¥, 日元
			Timezone: AsiaTokyo,
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "日本",
				language.ChineseHans: "日本",
				language.ChineseHant: "日本",
				language.English:     "Japan",
				language.French:      "Japon",
				language.German:      "Japan",
				language.Japanese:    "日本",
				language.Korean:      "일본",
				language.Russian:     "Япония",
				language.Spanish:     "Japón",
			},
		},
		"KR": {
			Code:             "KR",
			Name:             "대한민국",
			TelCode:          "+82",
			Domain:           ".kr",
			Banner:           "🇰🇷",
			ISO2:             "KR",
			ISO3:             "KOR",
			ISO3166:          "410",
			STANAG:           "KOR",
			GEC:              "KS",
			Capital:          "서울",
			NationalLanguage: language.Korean,
			Languages: []language.LanguageCode{
				language.Korean,
			},
			Currency: "KRW", // ₩, 韩元
			Timezone: AsiaSeoul,
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "韩国",
				language.ChineseHans: "韩国",
				language.ChineseHant: "韓國",
				language.English:     "Korea",
				language.French:      "Corée",
				language.German:      "Korea",
				language.Japanese:    "韓国",
				language.Korean:      "대한민국",
				language.Russian:     "Корея",
				language.Spanish:     "Corea",
			},
		},
		"GB": {
			Code:             "GB",
			Name:             "United Kingdom",
			TelCode:          "+44",
			Domain:           ".uk",
			Banner:           "🇬🇧",
			ISO2:             "GB",
			ISO3:             "GBR",
			ISO3166:          "826",
			STANAG:           "GBR",
			GEC:              "UK",
			Capital:          "London",
			NationalLanguage: language.English,
			Languages: []language.LanguageCode{
				language.English,
			},
			Currency: "GBP", // £, 英镑
			Timezone: EuropeLondon,
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "英国",
				language.ChineseHans: "英国",
				language.ChineseHant: "英國",
				language.English:     "United Kingdom",
				language.French:      "Royaume-Uni",
				language.German:      "Vereinigtes Königreich",
				language.Japanese:    "イギリス",
				language.Korean:      "영국",
				language.Russian:     "Великобритания",
				language.Spanish:     "Reino Unido",
			},
		},
		"DE": {
			Code:             "DE",
			Name:             "Deutschland",
			TelCode:          "+49",
			Domain:           ".de",
			Banner:           "🇩🇪",
			ISO2:             "DE",
			ISO3:             "DEU",
			ISO3166:          "276",
			STANAG:           "DEU",
			GEC:              "GM",
			Capital:          "Berlin",
			NationalLanguage: language.German,
			Languages: []language.LanguageCode{
				language.German,
			},
			Currency: "EUR", // €, 欧元
			Timezone: EuropeBerlin,
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "德国",
				language.ChineseHans: "德国",
				language.ChineseHant: "德國",
				language.English:     "Germany",
				language.French:      "Allemagne",
				language.German:      "Deutschland",
				language.Japanese:    "ドイツ",
				language.Korean:      "독일",
				language.Russian:     "Германия",
				language.Spanish:     "Alemania",
			},
		},
		"IT": {
			Code:             "IT",
			Name:             "Italia",
			TelCode:          "+39",
			Domain:           ".it",
			Banner:           "🇮🇹",
			ISO2:             "IT",
			ISO3:             "ITA",
			ISO3166:          "380",
			STANAG:           "ITA",
			GEC:              "IT",
			Capital:          "Rome",
			NationalLanguage: language.Italian,
			Languages: []language.LanguageCode{
				language.Italian,
			},
			Currency: "EUR", // €, 欧元
			Timezone: EuropeRome,
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "意大利",
				language.ChineseHans: "意大利",
				language.ChineseHant: "意大利",
				language.English:     "Italy",
				language.French:      "Italie",
				language.German:      "Italien",
				language.Japanese:    "イタリア",
				language.Korean:      "이탈리아",
				language.Russian:     "Италия",
				language.Spanish:     "Italia",
			},
		},
		"SG": {
			Code:             "SG",
			Name:             "Singapore",
			TelCode:          "+65",
			Domain:           ".sg",
			Banner:           "🇸🇬",
			ISO2:             "SG",
			ISO3:             "SGP",
			ISO3166:          "702",
			STANAG:           "SGP",
			GEC:              "SN",
			Capital:          "Singapore",
			NationalLanguage: language.English,
			Languages: []language.LanguageCode{
				language.English,
				language.Chinese,
			},
			Currency: "SGD", // $, 新加坡元
			Timezone: AsiaSingapore,
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "新加坡",
				language.ChineseHans: "新加坡",
				language.ChineseHant: "新加坡",
				language.English:     "Singapore",
				language.French:      "Singapour",
				language.German:      "Singapur",
				language.Japanese:    "シンガポール",
				language.Korean:      "싱가포르",
				language.Russian:     "Сингапур",
				language.Spanish:     "Singapur",
			},
		},
		"HK": {
			Code:             "HK",
			Name:             "Hong Kong",
			TelCode:          "+852",
			Domain:           ".hk",
			Banner:           "🇭🇰",
			ISO2:             "HK",
			ISO3:             "HKG",
			ISO3166:          "344",
			STANAG:           "HKG",
			GEC:              "HK",
			Capital:          "香港",
			NationalLanguage: language.Chinese,
			Languages: []language.LanguageCode{
				language.ChineseHant_HK,
				language.ChineseHant,
				language.Chinese,
			},
			Currency: "HKD", // $, 港币
			Timezone: AsiaHongKong,
			I18nName: map[language.LanguageCode]string{
				language.Chinese:        "香港",
				language.ChineseHans:    "香港",
				language.ChineseHant:    "香港",
				language.English:        "Hong Kong",
				language.French:         "Hong Kong",
				language.German:         "Hong Kong",
				language.Japanese:       "香港",
				language.Korean:         "홍콩",
				language.Russian:        "Гонконг",
				language.Spanish:        "Hong Kong",
				language.ChineseHant_HK: "香港",
			},
		},
		"TW": {
			Code:             "TW",
			Name:             "Taiwan",
			TelCode:          "+886",
			Domain:           ".tw",
			Banner:           "🇹🇼",
			ISO2:             "TW",
			ISO3:             "TWN",
			ISO3166:          "158",
			STANAG:           "TWN",
			GEC:              "TW",
			Capital:          "台北",
			NationalLanguage: language.Chinese,
			Languages: []language.LanguageCode{
				language.ChineseHant_TW,
				language.ChineseHant,
				language.Chinese,
			},
			Currency: "TWD", // $, 新台币
			Timezone: AsiaTaipei,
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "台湾",
				language.ChineseHans: "台湾",
				language.ChineseHant: "台灣",
				language.English:     "Taiwan",
				language.French:      "Taïwan",
				language.German:      "Taiwan",
				language.Japanese:    "台湾",
				language.Korean:      "대만",
				language.Russian:     "Тайвань",
				language.Spanish:     "Taiwán",
			},
		},
		"MO": {
			Code:             "MO",
			Name:             "Macau",
			TelCode:          "+853",
			Domain:           ".mo",
			ISO2:             "MO",
			ISO3:             "MAC",
			ISO3166:          "446",
			STANAG:           "MAC",
			GEC:              "MC",
			Capital:          "澳门",
			NationalLanguage: language.Chinese,
			Languages: []language.LanguageCode{
				language.ChineseHant_MO,
				language.ChineseHant,
				language.Chinese,
			},
			Currency: "MOP", // $, 澳门币
			Timezone: AsiaMacau,
			I18nName: map[language.LanguageCode]string{
				language.Chinese:        "澳门",
				language.ChineseHans:    "澳门",
				language.ChineseHant:    "澳門",
				language.English:        "Macau",
				language.French:         "Macao",
				language.German:         "Macao",
				language.Japanese:       "マカオ",
				language.Korean:         "마카오",
				language.Russian:        "Макао",
				language.Spanish:        "Macao",
				language.ChineseHant_MO: "澳門",
			},
		},
		"CA": {
			Code:             "CA",
			Name:             "Canada",
			TelCode:          "+1",
			Domain:           ".ca",
			Banner:           "🇨🇦",
			ISO2:             "CA",
			ISO3:             "CAN",
			ISO3166:          "124",
			STANAG:           "CAN",
			GEC:              "CA",
			Capital:          "Ottawa",
			NationalLanguage: language.English,
			Languages: []language.LanguageCode{
				language.English,
				language.French,
			},
			Currency: "CAD", // $, 加拿大元
			Timezone: AmericaToronto,
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "加拿大",
				language.ChineseHans: "加拿大",
				language.ChineseHant: "加拿大",
				language.English:     "Canada",
				language.French:      "Canada",
				language.German:      "Kanada",
				language.Japanese:    "カナダ",
				language.Korean:      "캐나다",
				language.Russian:     "Канада",
				language.Spanish:     "Canadá",
			},
		},
		"FR": {
			Code:             "FR",
			Name:             "France",
			TelCode:          "+33",
			Domain:           ".fr",
			ISO2:             "FR",
			ISO3:             "FRA",
			ISO3166:          "250",
			STANAG:           "FRA",
			GEC:              "FR",
			Capital:          "Paris",
			NationalLanguage: language.French,
			Languages: []language.LanguageCode{
				language.French,
			},
			Currency: "EUR", // €, 欧元
			Timezone: EuropeParis,
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "法国",
				language.ChineseHans: "法国",
				language.ChineseHant: "法國",
				language.English:     "France",
				language.French:      "France",
				language.German:      "Frankreich",
				language.Japanese:    "フランス",
				language.Korean:      "프랑스",
				language.Russian:     "Франция",
				language.Spanish:     "Francia",
			},
		},
		"NL": {
			Code:             "NL",
			Name:             "Netherlands",
			TelCode:          "+31",
			Domain:           ".nl",
			ISO2:             "NL",
			ISO3:             "NLD",
			ISO3166:          "528",
			STANAG:           "NLD",
			GEC:              "NL",
			Capital:          "Amsterdam",
			NationalLanguage: language.Dutch,
			Languages: []language.LanguageCode{
				language.Dutch,
			},
			Currency: "EUR", // €, 欧元
			Timezone: EuropeAmsterdam,
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "荷兰",
				language.ChineseHans: "荷兰",
				language.ChineseHant: "荷蘭",
				language.English:     "Netherlands",
				language.French:      "Pays-Bas",
				language.German:      "Niederlande",
				language.Japanese:    "オランダ",
				language.Korean:      "네덜란드",
				language.Russian:     "Нидерланды",
				language.Spanish:     "Países Bajos",
				language.Dutch:       "Nederland",
			},
		},

		// 完整的国家代码列表，按照国家代码排序
		"AD": {
			Code:             "AD",
			Name:             "Andorra",
			TelCode:          "+376",
			Domain:           ".ad",
			Banner:           "🇦🇩",
			ISO2:             "AD",
			ISO3:             "AND",
			ISO3166:          "020",
			STANAG:           "AND",
			GEC:              "AN",
			Capital:          "Andorra la Vella",
			NationalLanguage: language.Catalan,
			Languages: []language.LanguageCode{
				language.Catalan,
			},
			Currency: "EUR", // €, 欧元
			Timezone: EuropeAndorra,
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "安道尔",
				language.ChineseHans: "安道尔",
				language.ChineseHant: "安道爾",
				language.English:     "Andorra",
				language.French:      "Andorre",
				language.German:      "Andorra",
				language.Japanese:    "アンドラ",
				language.Korean:      "안도라",
				language.Russian:     "Андорра",
				language.Spanish:     "Andorra",
				language.Catalan:     "Andorra",
			},
		},
		"AE": {
			Code:             "AE",
			Name:             "United Arab Emirates",
			TelCode:          "+971",
			Domain:           ".ae",
			Banner:           "🇦🇪",
			ISO2:             "AE",
			ISO3:             "ARE",
			ISO3166:          "784",
			STANAG:           "ARE",
			GEC:              "AE",
			Capital:          "Abu Dhabi",
			NationalLanguage: language.Arabic,
			Languages: []language.LanguageCode{
				language.Arabic,
			},
			Currency: "AED", // د.إ, 阿联酋迪拉姆
			Timezone: AsiaDubai,
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "阿拉伯联合酋长国",
				language.ChineseHans: "阿拉伯联合酋长国",
				language.ChineseHant: "阿拉伯聯合酋長國",
				language.English:     "United Arab Emirates",
				language.French:      "Émirats arabes unis",
				language.German:      "Vereinigte Arabische Emirate",
				language.Japanese:    "アラブ首長国連邦",
				language.Korean:      "아랍에미리트 연합국",
				language.Russian:     "Объединенные Арабские Эмираты",
				language.Spanish:     "Emiratos Árabes Unidos",
				language.Arabic:      "الإمارات العربية المتحدة",
			},
		},
		"AF": {
			Code:             "AF",
			Name:             "Afghanistan",
			TelCode:          "+93",
			Domain:           ".af",
			Banner:           "🇦🇫",
			ISO2:             "AF",
			ISO3:             "AFG",
			ISO3166:          "004",
			STANAG:           "AFG",
			GEC:              "AF",
			Capital:          "Kabul",
			NationalLanguage: language.Dari,
			Languages: []language.LanguageCode{
				language.Dari,
				language.Pashto,
				language.Uzbek,
			},
			Currency: "AFN", // ؋, 阿富汗尼
			Timezone: AsiaKabul,
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "阿富汗",
				language.ChineseHans: "阿富汗",
				language.ChineseHant: "阿富汗",
				language.English:     "Afghanistan",
				language.French:      "Afghanistan",
				language.German:      "Afghanistan",
				language.Japanese:    "アフガニスタン",
				language.Korean:      "아프가니스탄",
				language.Russian:     "Афганистан",
				language.Spanish:     "Afganistán",
				language.Dari:        "افغانستان",
				language.Pashto:      "افغانستان",
				language.Uzbek:       "O'zbekiston",
			},
		},
		"AG": {
			Code:             "AG",
			Name:             "Antigua and Barbuda",
			TelCode:          "+1-268",
			Domain:           ".ag",
			Banner:           "🇦🇬",
			ISO2:             "AG",
			ISO3:             "ATG",
			ISO3166:          "028",
			STANAG:           "ATG",
			GEC:              "AC",
			Capital:          "Saint John's",
			NationalLanguage: language.English,
			Languages: []language.LanguageCode{
				language.English,
			},
			Currency: "XCD", // $, 东加勒比元
			Timezone: AmericaAntigua,
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "安提瓜和巴布达",
				language.ChineseHans: "安提瓜和巴布达",
				language.ChineseHant: "安提瓜和巴布達",
				language.English:     "Antigua and Barbuda",
				language.French:      "Antigua-et-Barbuda",
				language.German:      "Antigua und Barbuda",
				language.Japanese:    "アンティグア・バーブーダ",
				language.Korean:      "앤티가 바부다",
				language.Russian:     "Антигуа и Барбуда",
				language.Spanish:     "Antigua y Barbuda",
			},
		},
		"AI": {
			Code:             "AI",
			Name:             "Anguilla",
			TelCode:          "+1-264",
			Domain:           ".ai",
			Banner:           "🇦🇮",
			ISO2:             "AI",
			ISO3:             "AIA",
			ISO3166:          "660",
			STANAG:           "AIA",
			GEC:              "AV",
			Capital:          "The Valley",
			NationalLanguage: language.English,
			Languages: []language.LanguageCode{
				language.English,
			},
			Currency: "XCD", // $, 东加勒比元
			Timezone: AmericaAnguilla,
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "安圭拉",
				language.ChineseHans: "安圭拉",
				language.ChineseHant: "安圭拉",
				language.English:     "Anguilla",
				language.French:      "Anguilla",
				language.German:      "Anguilla",
				language.Japanese:    "アンギラ",
				language.Korean:      "앵귈라",
				language.Russian:     "Ангилья",
				language.Spanish:     "Anguila",
			},
		},
		"AL": {
			Code:             "AL",
			Name:             "Albania",
			TelCode:          "+355",
			Domain:           ".al",
			Banner:           "🇦🇱",
			ISO2:             "AL",
			ISO3:             "ALB",
			ISO3166:          "008",
			STANAG:           "ALB",
			GEC:              "AL",
			Capital:          "Tirana",
			NationalLanguage: language.Albanian,
			Languages: []language.LanguageCode{
				language.Albanian,
				language.Greek,
				language.Macedonian,
				language.Romanian,
				language.Serbian,
			},
			Currency: "ALL", // Lek, 阿尔巴尼亚列克
			Timezone: EuropeTirane,
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "阿尔巴尼亚",
				language.ChineseHans: "阿尔巴尼亚",
				language.ChineseHant: "阿爾巴尼亞",
				language.English:     "Albania",
				language.French:      "Albanie",
				language.German:      "Albanien",
				language.Japanese:    "アルバニア",
				language.Korean:      "알바니아",
				language.Russian:     "Албания",
				language.Spanish:     "Albania",
				language.Albanian:    "Shqipëria",
				language.Greek:       "Αλβανία",
				language.Macedonian:  "Албанија",
				language.Romanian:    "Albania",
				language.Serbian:     "Албанија",
			},
		},
		"AM": {
			Code:             "AM",
			Name:             "Armenia",
			TelCode:          "+374",
			Domain:           ".am",
			Banner:           "🇦🇲",
			ISO2:             "AM",
			ISO3:             "ARM",
			ISO3166:          "051",
			STANAG:           "ARM",
			GEC:              "AM",
			Capital:          "Yerevan",
			NationalLanguage: language.Armenian,
			Languages: []language.LanguageCode{
				language.Armenian,
				language.Russian,
			},
			Currency: "AMD", // դր., 亚美尼亚德拉姆
			Timezone: AsiaYerevan,
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "亚美尼亚",
				language.ChineseHans: "亚美尼亚",
				language.ChineseHant: "亞美尼亞",
				language.English:     "Armenia",
				language.French:      "Arménie",
				language.German:      "Armenien",
				language.Japanese:    "アルメニア",
				language.Korean:      "아르메니아",
				language.Russian:     "Армения",
				language.Spanish:     "Armenia",
				language.Armenian:    "Հայաստան",
			},
		},
		"AO": {
			Code:             "AO",
			Name:             "Angola",
			TelCode:          "+244",
			Domain:           ".ao",
			Banner:           "🇦🇴",
			ISO2:             "AO",
			ISO3:             "AGO",
			ISO3166:          "024",
			STANAG:           "AGO",
			GEC:              "AO",
			Capital:          "Luanda",
			NationalLanguage: language.Portuguese,
			Languages: []language.LanguageCode{
				language.Portuguese,
				language.Kikongo,
				language.Kwanyama,
				language.Lubwa,
				language.Lunda,
				language.NyanekaNkhumbi,
				language.NyanekaLuvale,
				language.NyanekaLuchazi,
				language.NyanekaLuchongwe,
				language.NyanekaLukonde,
				language.NyanekaLutumbuka,
				language.NyanekaLuchiluba,
			},
			Currency: "AOA", // Kz, 安哥拉宽扎
			Timezone: AfricaLuanda,
			I18nName: map[language.LanguageCode]string{
				language.Chinese:          "安哥拉",
				language.ChineseHans:      "安哥拉",
				language.ChineseHant:      "安哥拉",
				language.English:          "Angola",
				language.French:           "Angola",
				language.German:           "Angola",
				language.Japanese:         "アンゴラ",
				language.Korean:           "앙골라",
				language.Russian:          "Ангола",
				language.Spanish:          "Angola",
				language.Portuguese:       "Angola",
				language.Kikongo:          "Angola",
				language.Kwanyama:         "Angola",
				language.Lubwa:            "Angola",
				language.Lunda:            "Angola",
				language.NyanekaNkhumbi:   "Angola",
				language.NyanekaLuvale:    "Angola",
				language.NyanekaLuchazi:   "Angola",
				language.NyanekaLuchongwe: "Angola",
				language.NyanekaLukonde:   "Angola",
				language.NyanekaLutumbuka: "Angola",
				language.NyanekaLuchiluba: "Angola",
			},
		},
		"AR": {
			Code:             "AR",
			Name:             "Argentina",
			TelCode:          "+54",
			Domain:           ".ar",
			Banner:           "🇦🇷",
			ISO2:             "AR",
			ISO3:             "ARG",
			ISO3166:          "032",
			STANAG:           "ARG",
			GEC:              "AR",
			Capital:          "Buenos Aires",
			NationalLanguage: language.Spanish,
			Languages: []language.LanguageCode{
				language.Spanish,
				language.Guarani,
				language.Italian,
				language.German,
				language.English,
				language.French,
				language.Portuguese,
				language.Aymara,
				language.Mapudungun,
				language.Quechua,
				language.Tehuelche,
				language.Wichi,
			},
			Currency: "ARS", // $, 阿根廷比索
			Timezone: AmericaBuenosAires,
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "阿根廷",
				language.ChineseHans: "阿根廷",
				language.ChineseHant: "阿根廷",
				language.English:     "Argentina",
				language.French:      "Argentine",
				language.German:      "Argentinien",
				language.Japanese:    "アルゼンチン",
				language.Korean:      "아르헨티나",
				language.Russian:     "Аргентина",
				language.Spanish:     "Argentina",
				language.Guarani:     "Araguntin",
				language.Italian:     "Argentina",
				language.Portuguese:  "Argentina",
				language.Aymara:      "Araguntin",
				language.Quechua:     "Araguntin",
				language.Tehuelche:   "Araguntin",
			},
		},
		"AS": {
			Code:             "AS",
			Name:             "American Samoa",
			TelCode:          "+1-684",
			Domain:           ".as",
			Banner:           "🇦🇸",
			ISO2:             "AS",
			ISO3:             "ASM",
			ISO3166:          "016",
			STANAG:           "ASM",
			GEC:              "AS",
			Capital:          "Pago Pago",
			NationalLanguage: language.English,
			Languages: []language.LanguageCode{
				language.English,
				language.Samoan,
			},
			Currency: "USD", // $, 美元
			Timezone: PacificPagoPago,
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "美属萨摩亚",
				language.ChineseHans: "美属萨摩亚",
				language.ChineseHant: "美屬薩摩亞",
				language.English:     "American Samoa",
				language.French:      "Samoa américaines",
				language.German:      "Amerikanisch-Samoa",
				language.Japanese:    "アメリカ領サモア",
				language.Korean:      "아메리칸사모아",
				language.Russian:     "Американское Самоа",
				language.Spanish:     "Samoa Americana",
				language.Samoan:      "Amerika Sāmoa",
			},
		},
		"AT": {
			Code:             "AT",
			Name:             "Austria",
			TelCode:          "+43",
			Domain:           ".at",
			Banner:           "🇦🇹",
			ISO2:             "AT",
			ISO3:             "AUT",
			ISO3166:          "040",
			STANAG:           "AUT",
			GEC:              "AU",
			Capital:          "Vienna",
			NationalLanguage: language.German,
			Languages: []language.LanguageCode{
				language.German,
				language.German_AT,
			},
			Currency: "EUR", // €, 欧元
			Timezone: EuropeVienna,
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "奥地利",
				language.ChineseHans: "奥地利",
				language.ChineseHant: "奧地利",
				language.English:     "Austria",
				language.French:      "Autriche",
				language.German:      "Österreich",
				language.Japanese:    "オーストリア",
				language.Korean:      "오스트리아",
				language.Russian:     "Австрия",
				language.Spanish:     "Austria",
				language.German_AT:   "Österreich",
			},
		},
		"AU": {
			Code:             "AU",
			Name:             "Australia",
			TelCode:          "+61",
			Domain:           ".au",
			Banner:           "🇦🇺",
			ISO2:             "AU",
			ISO3:             "AUS",
			ISO3166:          "036",
			STANAG:           "AUS",
			GEC:              "AS",
			Capital:          "Canberra",
			NationalLanguage: language.English,
			Languages: []language.LanguageCode{
				language.English,
				language.English_AU,
			},
			Currency: "AUD", // $, 澳元
			Timezone: AustraliaCanberra,
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "澳大利亚",
				language.ChineseHans: "澳大利亚",
				language.ChineseHant: "澳大利亞",
				language.English:     "Australia",
				language.French:      "Australie",
				language.German:      "Australien",
				language.Japanese:    "オーストラリア",
				language.Korean:      "오스트레일리아",
				language.Russian:     "Австралия",
				language.Spanish:     "Australia",
				language.English_AU:  "Australia",
			},
		},
		"AW": {
			Code:             "AW",
			Name:             "Aruba",
			TelCode:          "+297",
			Domain:           ".aw",
			Banner:           "🇦🇼",
			ISO2:             "AW",
			ISO3:             "ABW",
			ISO3166:          "533",
			STANAG:           "ABW",
			GEC:              "AW",
			Capital:          "Oranjestad",
			NationalLanguage: language.Dutch,
			Languages: []language.LanguageCode{
				language.Dutch,
				language.English,
				language.Papiamento,
			},
			Currency: "AWG", // ƒ, 阿鲁巴盾
			Timezone: AmericaAruba,
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "阿鲁巴",
				language.ChineseHans: "阿鲁巴",
				language.ChineseHant: "阿魯巴",
				language.English:     "Aruba",
				language.French:      "Aruba",
				language.German:      "Aruba",
				language.Japanese:    "アルバ",
				language.Korean:      "아루바",
				language.Russian:     "Аруба",
				language.Spanish:     "Aruba",
				language.Papiamento:  "Aruba",
			},
		},
		"AX": {
			Code:             "AX",
			Name:             "Åland Islands",
			TelCode:          "+358",
			Domain:           ".ax",
			Banner:           "🇦🇽",
			ISO2:             "AX",
			ISO3:             "ALA",
			ISO3166:          "248",
			STANAG:           "ALA",
			GEC:              "AX",
			Capital:          "Mariehamn",
			NationalLanguage: language.Swedish,
			Languages: []language.LanguageCode{
				language.Swedish,
				language.Finnish,
				language.English,
			},
			Currency: "EUR", // €, 欧元
			Timezone: EuropeMariehamn,
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "奥兰群岛",
				language.ChineseHans: "奥兰群岛",
				language.ChineseHant: "奧蘭群島",
				language.English:     "Åland Islands",
				language.French:      "Åland",
				language.German:      "Åland",
				language.Japanese:    "オーランド諸島",
				language.Korean:      "올란드 제도",
				language.Russian:     "Аландские острова",
				language.Spanish:     "Alandia",
				language.Swedish:     "Åland",
				language.Finnish:     "Ahvenanmaa",
			},
		},
		"AZ": {
			Code:             "AZ",
			Name:             "Azerbaijan",
			TelCode:          "+994",
			Domain:           ".az",
			Banner:           "🇦🇿",
			ISO2:             "AZ",
			ISO3:             "AZE",
			ISO3166:          "031",
			STANAG:           "AZE",
			GEC:              "AZ",
			Capital:          "Baku",
			NationalLanguage: language.Azerbaijani,
			Languages: []language.LanguageCode{
				language.Azerbaijani,
				language.Russian,
				language.Turkish,
			},
			Currency: "AZN", // ₼, 阿塞拜疆马纳特
			Timezone: AsiaBaku,
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "阿塞拜疆",
				language.ChineseHans: "阿塞拜疆",
				language.ChineseHant: "阿塞拜疆",
				language.English:     "Azerbaijan",
				language.French:      "Azerbaïdjan",
				language.German:      "Aserbaidschan",
				language.Japanese:    "アゼルバイジャン",
				language.Korean:      "아제르바이잔",
				language.Russian:     "Азербайджан",
				language.Spanish:     "Azerbaiyán",
				language.Azerbaijani: "Azərbaycan",
				language.Turkish:     "Azerbaycan",
			},
		},
		"BA": {
			Code:             "BA",
			Name:             "Bosnia and Herzegovina",
			TelCode:          "+387",
			Domain:           ".ba",
			Banner:           "🇧🇦",
			ISO2:             "BA",
			ISO3:             "BIH",
			ISO3166:          "070",
			STANAG:           "BIH",
			GEC:              "BK",
			Capital:          "Sarajevo",
			NationalLanguage: language.Bosnian,
			Languages: []language.LanguageCode{
				language.Bosnian,
				language.Croatian,
				language.Serbian,
			},
			Currency: "BAM", // КМ, 波斯尼亚和黑塞哥维那可兑换马克
			Timezone: EuropeSarajevo,
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "波斯尼亚和黑塞哥维那",
				language.ChineseHans: "波斯尼亚和黑塞哥维那",
				language.ChineseHant: "波斯尼亞和黑塞哥維那",
				language.English:     "Bosnia and Herzegovina",
				language.French:      "Bosnie-Herzégovine",
				language.German:      "Bosnien und Herzegowina",
				language.Japanese:    "ボスニア・ヘルツェゴビナ",
				language.Korean:      "보스니아 헤르체고비나",
				language.Russian:     "Босния и Герцеговина",
				language.Spanish:     "Bosnia y Herzegovina",
				language.Bosnian:     "Bosna i Hercegovina",
				language.Croatian:    "Bosna i Hercegovina",
				language.Serbian:     "Босна и Херцеговина",
			},
		},
		"BB": {
			Code:    "BB",
			Name:    "Barbados",
			TelCode: "+1-246",
			Domain:  ".bb",
			Banner:  "🇧🇧",
			ISO2:    "BB",
			ISO3:    "BRB",
			ISO3166: "052",
			STANAG:  "BAR",
			GEC:     "BB",
			Capital: "Bridgetown",
			Languages: []language.LanguageCode{
				language.English,
			},
			Currency: "BBD", // $, 巴巴多斯元
			Timezone: AmericaBarbados,
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "巴巴多斯",
				language.ChineseHans: "巴巴多斯",
				language.ChineseHant: "巴巴多斯",
				language.English:     "Barbados",
				language.French:      "Barbade",
				language.German:      "Barbados",
				language.Japanese:    "バルバドス",
				language.Korean:      "바베이도스",
				language.Russian:     "Барбадос",
				language.Spanish:     "Barbados",
			},
		},
		"BD": {
			Code:    "BD",
			Name:    "Bangladesh",
			TelCode: "+880",
			Domain:  ".bd",
			Banner:  "🇧🇩",
			ISO2:    "BD",
			ISO3:    "BGD",
			ISO3166: "050",
			STANAG:  "BAN",
			GEC:     "BG",
			Capital: "Dhaka",
			Languages: []language.LanguageCode{
				language.Bengali,
				language.English,
			},
			Currency: "BDT", // ৳, 孟加拉塔卡
			Timezone: AsiaDhaka,
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "孟加拉国",
				language.ChineseHans: "孟加拉国",
				language.ChineseHant: "孟加拉國",
				language.English:     "Bangladesh",
				language.French:      "Bangladesh",
				language.German:      "Bangladesch",
				language.Japanese:    "バングラデシュ",
				language.Korean:      "방글라데시",
				language.Russian:     "Бангладеш",
				language.Spanish:     "Bangladesh",
			},
		},
		"BE": {
			Code:    "BE",
			Name:    "Belgium",
			TelCode: "+32",
			Domain:  ".be",
			Banner:  "🇧🇪",
			ISO2:    "BE",
			ISO3:    "BEL",
			ISO3166: "056",
			STANAG:  "BEL",
			GEC:     "BE",
			Capital: "Brussels",
			Languages: []language.LanguageCode{
				language.Dutch,
				language.French,
				language.German,
			},
			Currency: "EUR", // €, 欧元
			Timezone: EuropeBrussels,
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "比利时",
				language.ChineseHans: "比利时",
				language.ChineseHant: "比利時",
				language.English:     "Belgium",
				language.French:      "Belgique",
				language.German:      "Belgien",
				language.Japanese:    "ベルギー",
				language.Korean:      "벨기에",
				language.Russian:     "Бельгия",
				language.Spanish:     "Bélgica",
				language.Dutch:       "België",
			},
		},
		"BF": {
			Code:    "BF",
			Name:    "Burkina Faso",
			TelCode: "+226",
			Domain:  ".bf",
			Banner:  "🇧🇫",
			ISO2:    "BF",
			ISO3:    "BFA",
			ISO3166: "854",
			STANAG:  "BUR",
			GEC:     "UV",
			Capital: "Ouagadougou",
			Languages: []language.LanguageCode{
				language.French,
			},
			Currency: "XOF", // CFA Franc BCEAO, 西非法郎
			Timezone: AfricaOuagadougou,
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "布基纳法索",
				language.ChineseHans: "布基纳法索",
				language.ChineseHant: "布基納法索",
				language.English:     "Burkina Faso",
				language.French:      "Burkina Faso",
				language.German:      "Burkina Faso",
				language.Japanese:    "ブルキナファソ",
				language.Korean:      "부르키나파소",
				language.Russian:     "Буркина-Фасо",
				language.Spanish:     "Burkina Faso",
			},
		},
	}
)
