package area

import (
	"github.com/darabuchi/utils/language"
)

var (
	CurrencyCodeMap = map[string]*CurrencyInfo{
		"AED": {
			Code:   "AED",
			Name:   "阿联酋迪拉姆",
			Symbol: "د.إ",
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "阿联酋迪拉姆",
				language.ChineseHans: "阿联酋迪拉姆",
				language.ChineseHant: "阿聯酋迪拉姆",
				language.English:     "United Arab Emirates Dirham",
				language.French:      "Dirham des Émirats arabes unis",
				language.German:      "Dirham der Vereinigten Arabischen Emirate",
				language.Italian:     "Dirham degli Emirati Arabi Uniti",
				language.Japanese:    "アラブ首長国連邦ディルハム",
				language.Korean:      "아랍에미리트 디르함",
				language.Russian:     "Дирхам ОАЭ",
				language.Spanish:     "dírham de los Emiratos Árabes Unidos",
			},
		},
		"AFN": {
			Code:   "AFN",
			Name:   "阿富汗尼",
			Symbol: "؋",
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "阿富汗尼",
				language.ChineseHans: "阿富汗尼",
				language.ChineseHant: "阿富汗尼",
				language.English:     "Afghan Afghani",
				language.French:      "Afghani afghan",
				language.German:      "Afghanischer Afghani",
				language.Italian:     "Afghani afghano",
				language.Japanese:    "アフガニスタン・アフガニー",
				language.Korean:      "아프가니스탄 아프가니",
				language.Russian:     "Афгани",
				language.Spanish:     "afgani afgano",
			},
		},
		"ALL": {
			Code:   "ALL",
			Name:   "阿尔巴尼亚列克",
			Symbol: "Lek",
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "阿尔巴尼亚列克",
				language.ChineseHans: "阿尔巴尼亚列克",
				language.ChineseHant: "阿爾巴尼亞列克",
				language.English:     "Albanian Lek",
				language.French:      "Lek albanais",
				language.German:      "Albanischer Lek",
				language.Italian:     "Lek albanese",
				language.Japanese:    "アルバニア・レク",
				language.Korean:      "알바니아 렉",
				language.Russian:     "Албанский лек",
				language.Spanish:     "lek albanés",
			},
		},
		"AMD": {
			Code:   "AMD",
			Name:   "亚美尼亚德拉姆",
			Symbol: "֏",
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "亚美尼亚德拉姆",
				language.ChineseHans: "亚美尼亚德拉姆",
				language.ChineseHant: "亞美尼亞德拉姆",
				language.English:     "Armenian Dram",
				language.French:      "Dram arménien",
				language.German:      "Armenischer Dram",
				language.Italian:     "Dram armeno",
				language.Japanese:    "アルメニア・ドラム",
				language.Korean:      "아르메니아 드람",
				language.Russian:     "Армянский драм",
				language.Spanish:     "dram armenio",
			},
		},
		"ANG": {
			Code:   "ANG",
			Name:   "荷属安的列斯盾",
			Symbol: "ƒ",
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "荷属安的列斯盾",
				language.ChineseHans: "荷属安的列斯盾",
				language.ChineseHant: "荷屬安的列斯盾",
				language.English:     "Netherlands Antillean Guilder",
				language.French:      "Florin des Antilles néerlandaises",
				language.German:      "Niederländische-Antillen-Gulden",
				language.Italian:     "Fiorino delle Antille olandesi",
				language.Japanese:    "オランダ領アンティル・ギルダー",
				language.Korean:      "네덜란드령 안틸레스 길더",
				language.Russian:     "Гульден Нидерландских Антильских островов",
				language.Spanish:     "florín de las Antillas Neerlandesas",
			},
		},
		"AOA": {
			Code:   "AOA",
			Name:   "安哥拉宽扎",
			Symbol: "Kz",
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "安哥拉宽扎",
				language.ChineseHans: "安哥拉宽扎",
				language.ChineseHant: "安哥拉寬扎",
				language.English:     "Angolan Kwanza",
				language.French:      "Kwanza angolais",
				language.German:      "Angolanischer Kwanza",
				language.Italian:     "Kwanza angolano",
				language.Japanese:    "アンゴラ・クワンザ",
				language.Korean:      "앙골라 쿠안자",
				language.Russian:     "Ангольский кванза",
				language.Spanish:     "kwanza angoleño",
			},
		},
		"ARS": {
			Code:   "ARS",
			Name:   "阿根廷比索",
			Symbol: "$",
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "阿根廷比索",
				language.ChineseHans: "阿根廷比索",
				language.ChineseHant: "阿根廷比索",
				language.English:     "Argentine Peso",
				language.French:      "Peso argentin",
				language.German:      "Argentinischer Peso",
				language.Italian:     "Peso argentino",
				language.Japanese:    "アルゼンチン・ペソ",
				language.Korean:      "아르헨티나 페소",
				language.Russian:     "Аргентинское песо",
				language.Spanish:     "peso argentino",
			},
		},
		"AUD": {
			Code:   "AUD",
			Name:   "澳大利亚元",
			Symbol: "$",
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "澳大利亚元",
				language.ChineseHans: "澳大利亚元",
				language.ChineseHant: "澳大利亞元",
				language.English:     "Australian Dollar",
				language.French:      "Dollar australien",
				language.German:      "Australischer Dollar",
				language.Italian:     "Dollaro australiano",
				language.Japanese:    "オーストラリア・ドル",
				language.Korean:      "호주 달러",
				language.Russian:     "Австралийский доллар",
				language.Spanish:     "dólar australiano",
			},
		},
		"AWG": {
			Code:   "AWG",
			Name:   "阿鲁巴弗罗林",
			Symbol: "ƒ",
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "阿鲁巴弗罗林",
				language.ChineseHans: "阿鲁巴弗罗林",
				language.ChineseHant: "阿魯巴弗羅林",
				language.English:     "Aruban Florin",
				language.French:      "Florin arubais",
				language.German:      "Aruba-Florin",
				language.Italian:     "Florin arubano",
				language.Japanese:    "アルバ・フローリン",
				language.Korean:      "아루바 플로린",
				language.Russian:     "Арубанский флорин",
				language.Spanish:     "florín arubeño",
			},
		},
		"AZN": {
			Code:   "AZN",
			Name:   "阿塞拜疆马纳特",
			Symbol: "ман",
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "阿塞拜疆马纳特",
				language.ChineseHans: "阿塞拜疆马纳特",
				language.ChineseHant: "阿塞拜疆馬納特",
				language.English:     "Azerbaijani Manat",
				language.French:      "Manat azéri",
				language.German:      "Aserbaidschan-Manat",
				language.Italian:     "Manat azero",
				language.Japanese:    "アゼルバイジャン・マナト",
				language.Korean:      "아제르바이잔 마나트",
				language.Russian:     "Азербайджанский манат",
			},
		},
		"BAM": {
			Code:   "BAM",
			Name:   "波斯尼亚-黑塞哥维那可兑换马克",
			Symbol: "KM",
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "波斯尼亚-黑塞哥维那可兑换马克",
				language.ChineseHans: "波斯尼亚-黑塞哥维那可兑换马克",
				language.ChineseHant: "波斯尼亞-黑塞哥維那可兌換馬克",
				language.English:     "Bosnia and Herzegovina Convertible Mark",
				language.French:      "Mark convertible de Bosnie-Herzégovine",
				language.German:      "Konvertierbares Mark der Bosnien und Herzegowina",
				language.Italian:     "Marco convertibile della Bosnia ed Erzegovina",
				language.Japanese:    "ボスニア・ヘルツェゴビナ・コンバーティブル・マルク",
				language.Korean:      "보스니아 헤르체고비나 콘버티블 마르크",
				language.Russian:     "Конвертируемая марка Боснии и Герцеговины",
				language.Spanish:     "marco convertible de Bosnia y Herzegovina",
			},
		},
		"BBD": {
			Code:   "BBD",
			Name:   "巴巴多斯元",
			Symbol: "$",
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "巴巴多斯元",
				language.ChineseHans: "巴巴多斯元",
				language.ChineseHant: "巴巴多斯元",
				language.English:     "Barbadian Dollar",
				language.French:      "Dollar barbadien",
				language.German:      "Barbados-Dollar",
				language.Italian:     "Dollaro barbadiano",
				language.Japanese:    "バルバドス・ドル",
				language.Korean:      "바베이도스 달러",
				language.Russian:     "Барбадосский доллар",
				language.Spanish:     "dólar barbadense",
			},
		},
		"BDT": {
			Code:   "BDT",
			Name:   "孟加拉塔卡",
			Symbol: "৳",
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "孟加拉塔卡",
				language.ChineseHans: "孟加拉塔卡",
				language.ChineseHant: "孟加拉塔卡",
				language.English:     "Bangladeshi Taka",
				language.French:      "Taka bangladais",
				language.German:      "Taka",
				language.Italian:     "Taka bangladese",
				language.Japanese:    "バングラデシュ・タカ",
				language.Korean:      "방글라데시 타카",
				language.Russian:     "Бангладешская така",
				language.Spanish:     "taka de Bangladesh",
			},
		},
		"BGN": {
			Code:   "BGN",
			Name:   "保加利亚列弗",
			Symbol: "лв",
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "保加利亚列弗",
				language.ChineseHans: "保加利亚列弗",
				language.ChineseHant: "保加利亞列弗",
				language.English:     "Bulgarian Lev",
				language.French:      "Lev bulgare",
				language.German:      "Bulgarischer Lew",
				language.Italian:     "Lev bulgaro",
				language.Japanese:    "ブルガリア・レフ",
				language.Korean:      "불가리아 레프",
				language.Russian:     "Болгарский лев",
				language.Spanish:     "lev búlgaro",
			},
		},
		"BHD": {
			Code:   "BHD",
			Name:   "巴林第纳尔",
			Symbol: "د.ب",
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "巴林第纳尔",
				language.ChineseHans: "巴林第纳尔",
				language.ChineseHant: "巴林第納爾",
				language.English:     "Bahraini Dinar",
				language.French:      "Dinar bahreïni",
				language.German:      "Bahrain-Dinar",
				language.Italian:     "Dinaro del Bahrein",
				language.Japanese:    "バーレーン・ディナール",
				language.Korean:      "바레인 디나르",
				language.Russian:     "Бахрейнский динар",
				language.Spanish:     "dinar bahreiní",
			},
		},
		"BIF": {
			Code:   "BIF",
			Name:   "布隆迪法郎",
			Symbol: "Fr",
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "布隆迪法郎",
				language.ChineseHans: "布隆迪法郎",
				language.ChineseHant: "布隆迪法郎",
				language.English:     "Burundian Franc",
				language.French:      "Franc burundais",
				language.German:      "Burundi-Franc",
				language.Italian:     "Franco burundese",
				language.Japanese:    "ブルンジ・フラン",
				language.Korean:      "부룬디 프랑",
				language.Russian:     "Бурундийский франк",
				language.Spanish:     "franco burundés",
			},
		},
		"BMD": {
			Code:   "BMD",
			Name:   "百慕大元",
			Symbol: "$",
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "百慕大元",
				language.ChineseHans: "百慕大元",
				language.ChineseHant: "百慕大元",
				language.English:     "Bermudian Dollar",
				language.French:      "Dollar bermudien",
				language.German:      "Bermuda-Dollar",
				language.Italian:     "Dollaro delle Bermuda",
				language.Japanese:    "バミューダ・ドル",
				language.Korean:      "버뮤다 달러",
				language.Russian:     "Бермудский доллар",
				language.Spanish:     "dólar bermudeño",
			},
		},
		"BND": {
			Code:   "BND",
			Name:   "文莱元",
			Symbol: "$",
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "文莱元",
				language.ChineseHans: "文莱元",
				language.ChineseHant: "文萊元",
				language.English:     "Brunei Dollar",
				language.French:      "Dollar de Brunei",
				language.German:      "Brunei-Dollar",
				language.Italian:     "Dollaro del Brunei",
				language.Japanese:    "ブルネイ・ドル",
				language.Korean:      "브루나이 달러",
				language.Russian:     "Брунейский доллар",
				language.Spanish:     "dólar de Brunei",
			},
		},
		"BOB": {
			Code:   "BOB",
			Name:   "玻利维亚诺",
			Symbol: "Bs",
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "玻利维亚诺",
				language.ChineseHans: "玻利维亚诺",
				language.ChineseHant: "玻利維亞諾",
				language.English:     "Bolivian Boliviano",
				language.French:      "Boliviano bolivien",
				language.German:      "Bolivianischer Boliviano",
				language.Italian:     "Boliviano boliviano",
				language.Japanese:    "ボリビア・ボリビアーノ",
				language.Korean:      "볼리비아 볼리비아노",
				language.Russian:     "Боливийский боливиано",
				language.Spanish:     "boliviano boliviano",
			},
		},
		"BRL": {
			Code:   "BRL",
			Name:   "巴西雷亚尔",
			Symbol: "R$",
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "巴西雷亚尔",
				language.ChineseHans: "巴西雷亚尔",
				language.ChineseHant: "巴西雷亞爾",
				language.English:     "Brazilian Real",
				language.French:      "Réal brésilien",
				language.German:      "Brasilianischer Real",
				language.Italian:     "Real brasiliano",
				language.Japanese:    "ブラジル・レアル",
				language.Korean:      "브라질 레알",
				language.Russian:     "Бразильский реал",
				language.Spanish:     "real brasileño",
			},
		},
		"BSD": {
			Code:   "BSD",
			Name:   "巴哈马元",
			Symbol: "$",
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "巴哈马元",
				language.ChineseHans: "巴哈马元",
				language.ChineseHant: "巴哈馬元",
				language.English:     "Bahamian Dollar",
				language.French:      "Dollar bahaméen",
				language.German:      "Bahamianischer Dollar",
				language.Italian:     "Dollaro delle Bahamas",
				language.Japanese:    "バハマ・ドル",
				language.Korean:      "바하마 달러",
				language.Russian:     "Багамский доллар",
				language.Spanish:     "dólar bahameño",
			},
		},
		"BTN": {
			Code:   "BTN",
			Name:   "不丹努扎姆",
			Symbol: "Nu.",
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "不丹努扎姆",
				language.ChineseHans: "不丹努扎姆",
				language.ChineseHant: "不丹努扎姆",
				language.English:     "Bhutanese Ngultrum",
				language.French:      "Ngultrum bouthanais",
				language.German:      "Bhutanischer Ngultrum",
				language.Italian:     "Ngultrum bhutanese",
				language.Japanese:    "ブータン・ヌルトム",
				language.Korean:      "부탄 눌트럼",
				language.Russian:     "Бутанский нгултрум",
				language.Spanish:     "ngultrum butanés",
			},
		},
		"BWP": {
			Code:   "BWP",
			Name:   "博茨瓦纳普拉",
			Symbol: "P",
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "博茨瓦纳普拉",
				language.ChineseHans: "博茨瓦纳普拉",
				language.ChineseHant: "博茨瓦納普拉",
				language.English:     "Botswana Pula",
				language.French:      "Pula botswanais",
				language.German:      "Botswanischer Pula",
				language.Italian:     "Pula del Botswana",
				language.Japanese:    "ボツワナ・プラ",
				language.Korean:      "보츠와나 풀라",
				language.Russian:     "Ботсванская пула",
				language.Spanish:     "pula botswano",
			},
		},
		"BYN": {
			Code:   "BYN",
			Name:   "白俄罗斯卢布",
			Symbol: "Br",
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "白俄罗斯卢布",
				language.ChineseHans: "白俄罗斯卢布",
				language.ChineseHant: "白俄羅斯盧布",
				language.English:     "Belarusian Ruble",
				language.French:      "Rouble biélorusse",
				language.German:      "Weißrussischer Rubel",
				language.Italian:     "Rublo bielorusso",
				language.Japanese:    "ベラルーシ・ルーブル",
				language.Korean:      "벨라루스 루블",
				language.Russian:     "Белорусский рубль",
				language.Spanish:     "rublo bielorruso",
			},
		},
		"BZD": {
			Code:   "BZD",
			Name:   "伯利兹元",
			Symbol: "$",
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "伯利兹元",
				language.ChineseHans: "伯利兹元",
				language.ChineseHant: "伯利茲元",
				language.English:     "Belize Dollar",
				language.French:      "Dollar bélizien",
				language.German:      "Belize-Dollar",
				language.Italian:     "Dollaro del Belize",
				language.Japanese:    "ベリーズ・ドル",
				language.Korean:      "벨리즈 달러",
				language.Russian:     "Белизский доллар",
				language.Spanish:     "dólar beliceño",
			},
		},
		"CAD": {
			Code:   "CAD",
			Name:   "加拿大元",
			Symbol: "$",
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "加拿大元",
				language.ChineseHans: "加拿大元",
				language.ChineseHant: "加拿大元",
				language.English:     "Canadian Dollar",
				language.French:      "Dollar canadien",
				language.German:      "Kanadischer Dollar",
				language.Italian:     "Dollaro canadese",
				language.Japanese:    "カナダ・ドル",
				language.Korean:      "캐나다 달러",
				language.Russian:     "Канадский доллар",
				language.Spanish:     "dólar canadiense",
			},
		},
		"CDF": {
			Code:   "CDF",
			Name:   "刚果法郎",
			Symbol: "Fr",
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "刚果法郎",
				language.ChineseHans: "刚果法郎",
				language.ChineseHant: "剛果法郎",
				language.English:     "Congolese Franc",
				language.French:      "Franc congolais",
				language.German:      "Kongo-Franc",
				language.Italian:     "Franco congolese",
				language.Japanese:    "コンゴ・フラン",
				language.Korean:      "콩고 프랑",
				language.Russian:     "Конголезский франк",
				language.Spanish:     "franco congoleño",
			},
		},
		"CHF": {
			Code:   "CHF",
			Name:   "瑞士法郎",
			Symbol: "Fr",
			I18nName: map[language.LanguageCode]string{
				language.Chinese:     "瑞士法郎",
				language.ChineseHans: "瑞士法郎",
				language.ChineseHant: "瑞士法郎",
				language.English:     "Swiss Franc",
				language.French:      "Franc suisse",
				language.German:      "Schweizer Franken",
				language.Italian:     "Franco svizzero",
				language.Japanese:    "スイス・フラン",
				language.Korean:      "스위스 프랑",
				language.Russian:     "Швейцарский франк",
				language.Spanish:     "franco suizo",
			},
		},
	}
)
